### ISSUE TITLE
Request section?

### ISSUE THREAD

**Issue by ttiiggss** [github-tijlxyz/nostr.cooking#1]
Heyo!

Just wondering if a requests section could be accommodated? I was thinking of steak sauces in particular 😂 . But honestly, is this a feasible idea?

**Comment by ralyodio** [comment]
this would be cool

**Comment by github-tijlxyz** [comment]
Like another page with a list of things that people request? Can be done, but in this case I don't think that's worth it. It would maybe need a new Kind or just a simple kind 1 text note, but in that case you can also just post it on another client.

**Comment by BrutusBondBTC** [comment]
Does he mean another section like:
## Chef's Notes 

or a `steak sauce` tag?
