### ISSUE TITLE
Link previews to recipe URLs

### ISSUE THREAD

**Issue by InnocuousFinch** [github-tijlxyz/nostr.cooking#16]
When I send my someone a recipe (the full URL of a recipe), there is no link preview. It would be very useful to have link previews that show both the title and the image of the recipe. 

Below is what it looks like currently to send a recipe in text message: 

![image](https://github.com/github-tijlxyz/nostr.cooking/assets/118941419/cefa69a7-b135-4b47-810e-c91337419d22)

**Comment by sebdeveloper6952** [comment]
Are you guys looking for contributions? I am interested in contributing!

**Comment by chakany** [comment]
I tried to implement this simply, turns out it's not so simple.

Also closing this because i'm moving the project over to https://github.com/zapcooking/frontend
