### ISSUE TITLE
Undefined `firstTag` on `Recipe.svelte`

### ISSUE THREAD

**Issue by sebdeveloper6952** [github-tijlxyz/nostr.cooking#21]
Trying to browse a recipe this morning I stumbled upon the error:
<img width="403" alt="Screenshot 2024-03-28 at 10 06 53" src="https://github.com/github-tijlxyz/nostr.cooking/assets/18562903/4b8634e2-819c-4f1a-a3ab-021732242139">

Seems like commit 1a94d3d added a `firstTag` that is `undefined` and fails to render. I'm not sure of the purpose of this code so I can't provide a solution that makes sense.

**Comment by github-tijlxyz** [comment]
@chakany

**Comment by github-tijlxyz** [comment]
should be fixed in https://github.com/github-tijlxyz/nostr.cooking/commit/0b92ccd58d3c5d69b9e16a960faa42374440509d
