### ISSUE TITLE
Add npub search

### ISSUE THREAD

**Issue by Bevo21** [github-tijlxyz/nostr.cooking#3]
Hi mate can we add npub search to find creators, we need to be able to find plebs not just recipes. Thanks

**Comment by github-tijlxyz** [comment]
Hello,
There is a user page at https://nostr.cooking/user/npub12gu8c6uee3p243gez6cgk76362admlqe72aq3kp2fppjsjwmm7eqj9fle6
Real search does not really work with nostr tho.
Not sure if I know what you mean tho
