### ISSUE TITLE
Zaps not showing

### ISSUE THREAD

**Issue by Bevo21** [github-tijlxyz/nostr.cooking#6]
Zaps are not showing up on recipe, the recipe was zapped a few times but didnt show up, went back about 30 minutes later and it showed 1 zap only ( 21 sats ) . is there a time delay or a bug maybe??

https://nostr.cooking/recipe/8558a4ca0fcbf75cbb543133c4c25e3dd7fad97af93214b04ba7dbbcace7c12f

**Comment by github-tijlxyz** [comment]
Should be fixed with c10fdb0ff666e5b1c9bd8e07c3b9a19ef133ebfe!
