### ISSUE TITLE
Enable commenting

### ISSUE THREAD

**Issue by bitcoin21ideas** [github-tijlxyz/nostr.cooking#7]
Would be nice to enable comments to recipes. 

See how it looks on Habla (https://habla.news/tony/moscow-mule):

![comments](https://i.nostr.build/Pnld.jpg)

I'd look into https://github.com/fr4nzap/zapthreads for this.

**Comment by franzaps** [comment]
@github-tijlxyz if it sounds good to you I can send you a PR!

**Comment by franzaps** [comment]
Added `<zap-threads anchor={$page.params.slug} />`, needs some styling

![](https://image.nostr.build/b4c064b17a43d116c03f03ab0d94dc72a71935578b6ad15cfedaeae425352b2b.png)

**Comment by github-tijlxyz** [comment]
@fr4nzap Looks good! You're welcome to make a PR if you have think its integrated nicely.

**Comment by franzaps** [comment]
https://github.com/github-tijlxyz/nostr.cooking/pull/11

**Comment by github-tijlxyz** [comment]
Implemented in #11, thanks the @fr4nzap :)
