### ISSUE TITLE
Additional media block

### ISSUE THREAD

**Issue by bitcoin21ideas** [github-tijlxyz/nostr.cooking#8]
Would love to see an additional optional block for the chefs to be able to attach additional media (with a description) somewhere in the middle of the recipe, e.g. between Ingredients and Directions. They could add an extra image or even a short video to provide better understanding to the readers.

**Comment by github-tijlxyz** [comment]
You can already put a additional media in `Chef's Notes`, `Ingredients` and `Directions`.
You would need to use markdown format, example: 
```md
![alternate text](https://example.com/image.jpg)
```
[Here](https://nostr.cooking/recipe/naddr1qq9k6mmnvdhhwttdw4kx2q3qrl9wsktcp4mwssflh6kx0c6x5g59ny5hs7z4x7zq4p8qf433hs9sxpqqqp65wzclh3q) is a example recipe so you can see how it looks.
